### ISSUE TITLE
Add a page to show all devices in the room

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#10]
In the Lamps tab if the user press the name of the room (the read arrow point to it) 

<img src="https://user-images.githubusercontent.com/9304740/94470457-62f54a80-01d0-11eb-944d-669d115a0a78.jpeg" height="300">

the user moved to the [room page](https://github.com/CyBear-Jinni/CBJ_App/blob/master/FlutterApp/cybear_jinni_flutter/cybear_jinni_flutter/lib/features/room_page/room_page.dart).

In that screen we need to show all the devices that belong to that room, and have the functionality to turn them on and off.

It is not shown in the Lamps tab because the Lamps tab designed to show only 1-4 most used devices from each room for easy access.

**Comment by nayakastha** [comment]
Hey! Can you assign it to me? I will submit a PR in October as HacktoberFest starts

**Comment by guyluz11** [comment]
Sounds good, it is yours

**Comment by guyluz11** [comment]
Update!

A default test `google cloud Firebase` configuration was add to the app so for developers you only need to run the app on the phone and it should work.

Thanks

**Comment by guyluz11** [comment]
Done
