### ISSUE TITLE
broken links on Instructions for developers

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_App#118]
On the wiki page of this repo inside instructions for developers there is this text :

![image](https://user-images.githubusercontent.com/34707669/101224651-f139f100-3697-11eb-9b95-ca45216eabe4.png)

But the "flutter project" link is broken and leads to a 404 page:

![image](https://user-images.githubusercontent.com/34707669/101224704-19295480-3698-11eb-833b-70cb04d43bf0.png)

You may want to show a link to your flutter project:

[flutter project](https://github.com/CyBear-Jinni/CBJ_App)

----

Another broken link can be found here:

![image](https://user-images.githubusercontent.com/34707669/101225222-91444a00-3699-11eb-8958-4264874b91b7.png)

I think that you wanted to show this link:

[constant_credentials.dart](https://github.com/CyBear-Jinni/CBJ_App/blob/master/lib/core/constant_credentials.dart)

---

There is also this link:

![image](https://user-images.githubusercontent.com/34707669/101224824-7ae9be80-3698-11eb-9d1a-720e93c369f2.png)

I think that this was not intended to be a link, maybe you can consider it to be wrapped in a code block like this:

` .../android/app/`

Or even simply bold the text **.../android/app/**

**If this was meant to be a link please use this link instead:**

[.../android/app/](https://github.com/CyBear-Jinni/CBJ_App/find/master)

**Comment by guyluz11** [comment]
I have updated the links to the correct path.

Can you check now?.

Thanks

**Comment by Tamir198** [comment]
> ou check n

I will check it again

**Comment by Tamir198** [comment]
@guyluz11 
Look good now, good job 🥇
