### ISSUE TITLE
Adding local storage

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#12]
Currently we have static dart file called [cloud_interface_data.dart](https://github.com/CyBear-Jinni/CBJ_App/blob/master/lib/objects/interface_darta/cloud_interface_data.dart) that stores all the devices in the home.

When adding new device from the application menu it disappear after restart of the application.
We need to add local storage that will save all the devices after the application is closed.

The local storage will be used for (you only need to implement the first one):
* Keeping a list of all the SmartRoomObject (that contain inside rooms and smart devices in each room).
* This data will be updated from and to the Cloud fire store.
* This data will be updated through WiFi and from WiFi (devices will share configuration with each other).
* Support multiple platforms is a plus (phones browser desktop).
* In the future a lot more like pictures and application settings preference.

Choosing local storage/database package is a big part in this project so lets discuss this before starting the work, this way we will do the best choice for this project.

You can contact me on the discord channel

[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)

**Comment by masterashu** [comment]
I believe this is the correct link for [cloud_interface_data.dart](https://github.com/CyBear-Jinni/CBJ_App/blob/master/lib/objects/interface_darta/cloud_interface_data.dart).

**Comment by guyluz11** [comment]
Thanks @masterashu 
I will update it now in the issue

**Comment by krish-bhanushali** [comment]
Can I try working on this?

**Comment by guyluz11** [comment]
Sounds great @krish-bhanushali

**Comment by guyluz11** [comment]
As firestore have local storage implemented, I have add Hive local storage only for home ID for now.
Thanks
