### ISSUE TITLE
App registration suggestion

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_App#120]
When a new user is creating his account for the app, the very next thing that he will see is the empty login page.

Suggestion:

When you redirect the user to the login page (after creating a new account) you can show him his email on the login page.
This will prevent your user from writing the same email again, it may not take a long time but it is affecting the user experience.

**Comment by guyluz11** [comment]
I think that even better option is to log in the user straight after registration is complete successfully.

**Comment by Tamir198** [comment]
> better option is to log in the u

This is actually a better option.

**Comment by guyluz11** [comment]
> I think that even better option is to log in the user straight after registration is complete successfully.

This functionality has been implemented.

Thanks
