### ISSUE TITLE
creating new user with already existing email

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_App#123]
If I will  go to create a new user and enter an already existing email (like below) pressing the create a new account will do nothing :

![image](https://user-images.githubusercontent.com/34707669/101295116-460a7280-3824-11eb-8cd3-7cc6e5eeae98.png)

I think that if that email is already in use, maybe it is a good thing to notify the user with a "Email Already in use" message  or something similar.

Otherwise, it may seem to the user like the create a new account button is just not working.

**Comment by guyluz11** [comment]
Nice one.
I think that toast message to show errors will be good.

**Comment by guyluz11** [comment]
On second thought it is better not to show toast as it will be less convenient on big screen/web site on desktop, and we want to code once where it is possible.

**Comment by guyluz11** [comment]
Fixed, Thanks
