### ISSUE TITLE
Minimum password length is not showing in Create a new account page

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_App#125]
Inside the Create a new account page I am getting this message when trying to add a short password

![image](https://user-images.githubusercontent.com/34707669/101295406-2e33ee00-3826-11eb-96d9-c80ccb0261db.png)

Notice that the text contains { } and not an actual number.

This but is only occurring in the "create new account page", in the login page this works just fine.

**Comment by guyluz11** [comment]
So if it is working in login page and it is the same validation we can extract the validation and call it from both places.

**Comment by guyluz11** [comment]
Fixed, Thanks
