### ISSUE TITLE
I can add blank password made of tabs

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_App#126]
Both in the login page and in the create a new user  there is a requirement that the password and the email should not contain any spaces:

![image](https://user-images.githubusercontent.com/34707669/101295713-06458a00-3828-11eb-949b-63db5fed12cb.png)

This works fine if I try to enter spaces, but I can enter a password and email that only contains tabs.
In this case, the app will act just as everything is normal and there was not a single space entered from the user.

**Comment by guyluz11** [comment]
Interesting.
We should change the tab functionality at all.
It's needs to be the next field and in the last one close the keyboard.

**Comment by Tamir198** [comment]
> Interesting.
> We should change the tab functionality at all.
> It's should to be the next field and in the last one close the keyboard.

I have edited my issue, this is also occurring in the email field, currently `test test@test.com` is count as a valid email.

**Comment by guyluz11** [comment]
Fixed for the email field.

**Comment by guyluz11** [comment]
It is fixed for only the email, not for password.
So I am reopening this issue.

**Comment by AvielCo** [comment]
I will try to solve it.

**Comment by AvielCo** [comment]
As I said in the PR (#199), I fixed this issue; For email and password fields.

**Comment by guyluz11** [comment]
Merged the pull request and tested it.
Thanks @Tamir198  and @AvielCo .

Will close this issue now.
