### ISSUE TITLE
New "Forgot password" page is required 

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#13]
In the login page we have "Forgot password?" text that does not do anything.

When the user pressing the text he need to move to different page and insert his details to reset his password using the [FireBase api](https://pub.dev/packages/cloud_firestore) .

For now pleas do it without functionality as we don't want it to collide with #5  and have duplicated code to control FireBase. 

<img src="https://user-images.githubusercontent.com/9304740/94589741-56372c00-028e-11eb-9193-351321dd73b4.jpeg" height="300">

- [x] Add forgot password page to the app.
- [ ] Add functionality to it using FireBase api.

**Comment by guyluz11** [comment]
@elaishane

**Comment by elaishane** [comment]
Can you assign me this issue?

**Comment by guyluz11** [comment]
It is yours

**Comment by guyluz11** [comment]
Update!

A default test `google cloud Firebase` configuration was add to the app so for developers you only need to run the app on the phone and it should work.

Thanks

**Comment by guyluz11** [comment]
The app just got support for creating new account and login with user.

So add to this ticket the task to not only create the page but to add the functionality to it.

Thanks

**Comment by idanre** [comment]
hi i'm working on the issue :)

**Comment by guyluz11** [comment]
Sure

**Comment by guyluz11** [comment]
Thanks @idanre part one is was merged.
I am removing you from the  `Assignees`  tage.
If you want to take part two which is `Add functionality to it using FireBase api.` please tell me and I will put you again.

**Comment by guyluz11** [comment]
Forgot password page will not be available for now.
We discovered that it can make problems for the smart devices which using the admin user account to communicate with firebase database.

So I am closing this issue.

Thanks all.
