### ISSUE TITLE
App icon need to be changed

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#17]
As we just got nice [new icon](https://github.com/CyBear-Jinni/CBJ_Site/tree/master/fan_art) from our [create fan art issue](https://github.com/CyBear-Jinni/CBJ_Site/issues/1) we are going to update it everywhere in the app.

All the [images of the owl (logo.png)](https://github.com/CyBear-Jinni/CBJ_App/blob/master/FlutterApp/cybear_jinni_flutter/cybear_jinni_flutter/assets/logo.png) in the app should be updated to the new logo.

That's include the icon of the app, the image in the splash screen, the image in the login page.

If more places exist please change it as well 

Please change the name of the file from `logo` to `cbj_logo` .

Here is an image of the logo that I removed the background.
You will probably need to change the dimensions of the image to the right ones.

<img src="https://user-images.githubusercontent.com/9304740/94843279-24a49900-0425-11eb-83f3-87e8ba40b1dc.png" height="300">

**Comment by AgungPrabowo** [comment]
hi @guyluz11, You can assign this issue to me?

**Comment by duythien0912** [comment]
This logo looks fun lol

**Comment by Capt-Titanium** [comment]
Heyy @guyluz11 , I would like to do this issue!

**Comment by guyluz11** [comment]
@duythien0912 the [create fan art issue](https://github.com/CyBear-Jinni/CBJ_Site/issues/1) is open to for everyone without limit.

So if you want to join feel free and get easy pull request XD .

**Comment by guyluz11** [comment]
@Capt-Titanium Go for it. 

Thanks

**Comment by guyluz11** [comment]
Update!

A default test `google cloud Firebase` configuration was add to the app so for developers you only need to run the app on the phone and it should work.

Thanks

**Comment by guyluz11** [comment]
@Capt-Titanium 
I got confused with some pull request and did the icon change for you.
Please do [this](https://github.com/WaAlvis/CBJ_App/pull/1) pull request yourself to get the Hacktoberfest accept it.

If his branch is deleted you can view this [here](https://github.com/guyluz11/CBJ_App/commit/45fa896e9094e4728c8bd1973d4df6d4212ac0c1) too.

**Comment by Capt-Titanium** [comment]
Sure, I will do the same changes myself but I need to update my sdk so I will be able to do it when I have installed it. Is it okay if I take a few more days?

**Comment by guyluz11** [comment]
@Capt-Titanium yes this is ok

**Comment by guyluz11** [comment]
App icon has been changed.
