### ISSUE TITLE
The app can be found on play store

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_App#177]
Please update README, now that you have [uploaded the app to play store](https://play.google.com/store/apps/details?id=com.cybear_jinni.smart_home&gl=IL) your current readme is not up to date.

**Comment by guyluz11** [comment]
Thanks, will add it in the next few days

**Comment by guyluz11** [comment]
![playstore logo](https://user-images.githubusercontent.com/9304740/117003444-8b58a080-aced-11eb-94bc-bfb2505f515d.png)

This google play logo will be used in the README

**Comment by guyluz11** [comment]
Done.
Thanks for opening the issue.
