### ISSUE TITLE
the google-services.json file is missing

### ISSUE THREAD

**Issue by AgungPrabowo** [CyBear-Jinni/CBJ_App#18]
I can't run the application because there is no google-services.json file, is there a solution?

**Comment by guyluz11** [comment]
Hi @AgungPrabowo 

We currently do not upload the `google-services.json` to the public repository from security standpoint.

We have instructions on how to create one and insert it in the readme file [Instructions for developers part](https://github.com/CyBear-Jinni/CBJ_App#instructions-for-developers).

You can reach me in Discord and I will help you with that.

[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)

**Comment by guyluz11** [comment]
Thanks @AgungPrabowo 

The part
"his part is only required if you are going to connect the application to the smart devices, if not you can just run the app without extra steps." 

was moved in dev branch to the correct place thanks to you :D,
you do need to add the Firebase part in order for the app to work.



It will be merged to master in the coming days.
