### ISSUE TITLE
Add plus button for all the main pages.

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#205]
Floating plus button in the bottom right corner is needed for easy user interface to add new items.

The button need to be add to the following pages: `Scenes`, `Devices`, `Routines`, `Linked`.

**Comment by samordoch** [comment]
no problem i will do it

**Comment by chena-1** [comment]
I will do it.

**Comment by guyluz11** [comment]
Thanks for the pull request.
I have merged it, closing this issue now.
