### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#226]
As we uploaded the app to snap #210 we need to add link to it in the readme file

Link to the app snapstore page:
https://snapcraft.io/cybear-jinni

**Comment by danger-ahead** [comment]
Hi I can do this. Please consider assigning me!

**Comment by guyluz11** [comment]
Sure
Please do it in the same way the snap represented in here
https://github.com/CyBear-Jinni/CBJ_Smart-Device

Once here
![image](https://user-images.githubusercontent.com/9304740/127768200-f3c463c7-26ac-47a6-90dd-bae2b58867fa.png)

And again like this
![image](https://user-images.githubusercontent.com/9304740/127768215-afb95cde-2af1-46d7-a4da-ab7e5a132537.png)
in the same row as the play store button.

Thanks

**Comment by guyluz11** [comment]
Thanks @danger-ahead for the help.

**Comment by guyluz11** [comment]
Feel free to join the discord channel in case you want to contribute more or discuss with us.

[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)
