### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#227]
The app just got support to run on Linux.

Adding Windows support should be easy too.

Please add support and post a screenshot here of in running :)

**Comment by chena-1** [comment]
I will do it

**Comment by guyluz11** [comment]
Uploading the image from the pull request
![image](https://user-images.githubusercontent.com/9304740/126860674-7d82c4f7-4c2a-429e-b98f-a49f8b5862a5.png)

Thanks @chena-1 looks good.

**Comment by guyluz11** [comment]
@chena-1 see also #231 if you are interested.
