### ISSUE TITLE
 Windows app change defaults

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#231]
Our windows app have some defaults.

Name at the top left is cbj_app should be CyBear Jinni

Logo of the company is the flutter logo should be the panda logo.

More?:
My guess is that the process name of the app is also different from CyBear Jinni.

Name of the app after compiling with `flutter build windows` should also probably changed to CyBear Jinni App.

![image](https://user-images.githubusercontent.com/9304740/126860706-59b17aae-5563-4f86-b087-739f9430f114.png)

**Comment by guyluz11** [comment]
For the panda logo you can find some in the `assets` folder.
For different resolutions please comment here with the dimensions.

**Comment by chena-1** [comment]
I will do it

**Comment by guyluz11** [comment]
@chena-1 

Also change `com.cybear-jinni` occurrences to `com.cybear-jinni.smart-home`

**Comment by guyluz11** [comment]
Thanks @chena-1 
I have merged the pull request and will now close the issue.
