### ISSUE TITLE
Getting Firebase data from the file google-services.json file into the app

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#26]
While setting up the app developers need to insert `fireBaseProjectId` and `fireBaseApiKey` manually from
 `google-services.json` file to [constant_credentials.dart](https://github.com/CyBear-Jinni/CBJ_App/blob/master/lib/core/constant_credentials.dart) file.

This is needed in order to too transfer it to the [CyBear Jinni Smart Device](https://github.com/CyBear-Jinni/CBJ_Smart-Device) so that the device will be able to connect to the cloud Firebase as well.

Please make the app add  programmatically `project_id` and `current_key` from the  `google-services.json` file into the file [constant_credentials.dart](https://github.com/CyBear-Jinni/CBJ_App/blob/master/lib/core/constant_credentials.dart).

**Comment by masterashu** [comment]
I would like to work on it.

**Comment by guyluz11** [comment]
Update!

A default test `google cloud Firebase` configuration was add to the app so for developers you only need to run the app on the phone and it should work.

Thanks

**Comment by masterashu** [comment]
I created a PR.
This is how the process looks now.

[![asciicast](https://asciinema.org/a/363215.svg)](https://asciinema.org/a/363215)

**Comment by guyluz11** [comment]
Inserting firebase data manually on runtime is not an option as it will create security vulnerabilities and a lot of overhead just to make it work.
We may add other database option in the future that will make it possible to insert user database on runtime with them but not for firebase.
So I am closing this issue.

I am keeping the script pull request open for now.

Thanks @masterashu for your time and help.
