### ISSUE TITLE
Adding badges to readme

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#27]
Please make the readme top part same as [this](https://github.com/CyBear-Jinni/CBJ_Smart-Device/blob/master/README.md) readme.

[<img src="https://user-images.githubusercontent.com/9304740/94920772-97fae900-04bf-11eb-9501-2b43950efe66.png" height="300">](https://discord.gg/mUXfwUY)

Don't forget to change the title to `CyBear Jinni App` and the link to the `dart cli` badge to this project action.

**Comment by SPOCTONE** [comment]
Please assign.

**Comment by Tejas99999** [comment]
can i do it

**Comment by LON3WO7F** [comment]
Hey @guyluz11 
I'm a little bit confused about this issue.
Just wanna know what I have to do in this?

**Comment by guyluz11** [comment]
Hi @SPOCTONE 
I am assigning it to you.

**Comment by guyluz11** [comment]
Hello @Tejas99999  @SPOCTONE 

I am creating similar issues for the readme, if you want to take one please get in touch with me in the Discord so that I can put it to you as son as it is published.

[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)

**Comment by SPOCTONE** [comment]
> Hello @Tejas99999 @SPOCTONE
> 
> I am creating similar issues for the readme, if you want to take one please get in touch with me in the Discord so that I can put it to you as son as it is published.
> 
> [<img alt="" height="80" src="https://camo.githubusercontent.com/f3c2a605703e1c5756c26fa807d7e66edc057ef2/68747470733a2f2f63646e2e69636f6e2d69636f6e732e636f6d2f69636f6e73322f323130382f504e472f3531322f646973636f72645f69636f6e5f3133303935382e706e67">](https://discord.gg/mUXfwUY)

For sure! looking forward to it. meanwhile I'm creating a PR fir this issue ASAP.

**Comment by guyluz11** [comment]
@LON3WO7F 

I am creating similar issues for the readme, if you want to take one please get in touch with me in the Discord so that I can put it to you as son as it is published.

[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)

**Comment by guyluz11** [comment]
Thanks @SPOCTONE  for the pull request.

Closing this issue now
