### ISSUE TITLE
Will you join hacktoberfest 2021?

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/cbj_app#272]
Hey, last year was super fun during hacktoberfest and I wanted to ask if you (well, the repos) will take part hacktoberfest this year?

Thank you

**Comment by guyluz11** [comment]
Hy @Tamir198, we surely intend to join hacktoberfest.

As CyBear Jinni got created from a place of helping the world and building the future together we have a big place for the open-source community.
In addition to that we also welcome all the exposure that we get from that, it helps us grow bigger and stronger and help us keep moving forward.

I am happy to hear that you are interested to join us again this year 😃.
