### ISSUE TITLE
Snap icon does not show in os's app launchers

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#273]
After downloading a snap the icon of the snap should be added to the app launchers of the different Linux os's.
We are probably missing a small section in the snapcraft.yaml that will set it up with app icon and all.

![image](https://user-images.githubusercontent.com/9304740/132122625-2b2aec58-7083-4b6f-8d7d-36853fd4bf06.png)

The snapcraft.yaml file can be found in the app snap repo

https://github.com/CyBear-Jinni-user/CBJ_App_Snap

**Comment by guyluz11** [comment]
Logo for the snap icon

CyBear Jinni app logo no background 256x256
https://user-images.githubusercontent.com/9304740/132479923-a94aa095-3cf5-4e08-a2ea-d3f9593144e2.png
![CyBear Jinni app logo no background 256x256](https://user-images.githubusercontent.com/9304740/132479923-a94aa095-3cf5-4e08-a2ea-d3f9593144e2.png)

CyBear Jinni app logo no background 512x512
https://user-images.githubusercontent.com/9304740/132479926-ee02c36a-98c1-4c25-877e-0855236b00d2.png
![CyBear Jinni app logo no background 512x512](https://user-images.githubusercontent.com/9304740/132479926-ee02c36a-98c1-4c25-877e-0855236b00d2.png)

CyBear Jinni app logo no background 1024x1024
https://user-images.githubusercontent.com/9304740/132479928-7430c327-86c8-4b0e-8a22-6197da0cd1b8.png
![CyBear Jinni app logo no background 1024x1024](https://user-images.githubusercontent.com/9304740/132479928-7430c327-86c8-4b0e-8a22-6197da0cd1b8.png)

**Comment by shikharvashistha** [comment]
Greetings of the day @guyluz11, 

I would be happy to work on this issue

Thanks & Regards
Shikhar Vashistha

**Comment by guyluz11** [comment]
@shikharvashistha sure, this issue is now in your hands :) .

**Comment by guyluz11** [comment]
I have accidentally closed the Issue without checking.
There was an error building the snap, I have fixed it (build using flutter stable instead of flutter master).

Now after building the snap I still can't see our snap logo in my luncher running on Kubuntu.
Can your try installing the snap on your Linux machine and report?, it can be downloaded from the [last stable release in the snap store](https://snapcraft.io/cybear-jinni).

**Comment by shikharvashistha** [comment]
> I have accidentally closed the Issue without checking.
> There was an error building the snap, I have fixed it (build using flutter stable instead of flutter master).
> 
> Now after building the snap I still can't see our snap logo in my luncher running on Kubuntu.
> Can your try installing the snap on your Linux machine and report?, it can be downloaded from the [last stable release in the snap store](https://snapcraft.io/cybear-jinni).

Reference used : [here](https://bugs.launchpad.net/developer-ubuntu-com/+bug/1578231)

**Comment by guyluz11** [comment]
Found this while creating the snap

```
The 'snap' directory is meant specifically for snapcraft, but it contains the following non-snapcraft-related paths, which is unsupported and will cause unexpected behavior:
- setup
- setup/gui
- setup/gui/icon.png

If you must store these files within the 'snap' directory, move them to 'snap/local', which is ignored by snapcraft.
```

I think what you referenced is deprecated.

**Comment by shikharvashistha** [comment]
> Found this while creating the snap
> 
> ```
> The 'snap' directory is meant specifically for snapcraft, but it contains the following non-snapcraft-related paths, which is unsupported and will cause unexpected behavior:
> - setup
> - setup/gui
> - setup/gui/icon.png
> 
> If you must store these files within the 'snap' directory, move them to 'snap/local', which is ignored by snapcraft.
> ```
> 
> I think what you referenced is deprecated.

Greetings of the day @guyluz11,

I've also gone through the official documentation [here](https://github.com/elopio/snapcraft/blob/db6d4ea1a65ff920fe57f7f8ec27f58db4966c13/docs/your-first-snap.md#snap-icon) and it suggests the same.

Thanks & Regards
@shikharvashistha

**Comment by guyluz11** [comment]
As you can see in my picture this is only a fork of the official documentation, and it is was last updated in 2016.

![image](https://user-images.githubusercontent.com/9304740/132945168-5c814c47-c94b-4405-be0b-485d0dd37303.png)

**Comment by shikharvashistha** [comment]
Greetings of the day,

The icon could be added in [this](https://askubuntu.com/questions/800685/add-a-snap-icon-to-the-desktop-ubuntu-16-04#801422) way. What do you suggest ?

Thanks & Regards 
@shikharvashistha

**Comment by guyluz11** [comment]
@shikharvashistha Your first link from StackExchange askUbuntu is also from 2016.
I think your second link is ok and another good place that I found is from [snapcraft-yaml-reference](https://snapcraft.io/docs/snapcraft-yaml-reference#icon) in the icon section

> Note that the desktop menu does not use this icon. It uses the icon in the .desktop file of the application.

**Comment by shikharvashistha** [comment]
> @shikharvashistha Your first link from StackExchange askUbuntu is also from 2016.
> I think your second link is ok and another good place that I found is from [snapcraft-yaml-reference](https://snapcraft.io/docs/snapcraft-yaml-reference#icon) in the icon section
> 
> > Note that the desktop menu does not use this icon. It uses the icon in the .desktop file of the application.
> 
> Under `apps. <app-name>. autostart` it is written about .desktop file
> 
> ```
> the name of the autostart .desktop file.
> Type: string
> The desktop file is placed in $SNAP_USER_DATA/.config/autostart, and the application is started using the app’s command wrapper. See Snapcraft parts metadata for further details.
> ```
> 
> Also an example of one that works is always good, I have found one (didn't test it but looks good)
> 
> https://github.com/ferraridamiano/ConverterNOW/tree/master/snap/gui
> 
> It looks like we are missing a `cybear-jinni.desktop` file and the `snap/gui/icon` should work but I think using `snap/gui/icon` is old method and we should not use it.

Greetings of the day @guyluz11,

I guess both of the links (one provided by and you) suggest the same. I've created a pull [here](https://github.com/CyBear-Jinni-user/CBJ_App_Snap/pull/2)

Thanks & Regards
@shikharvashistha

**Comment by guyluz11** [comment]
Looks good

![image](https://user-images.githubusercontent.com/9304740/133224848-ba8df5a5-ec11-4dbe-8d2a-2849f63a62eb.png)


Will close now the issue.

Thanks @shikharvashistha for all the help
