### ISSUE TITLE
The icon in readme should be using the new CyBear Jinni mascot  

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#278]
The mascot should be edited to be inside a smartphone similar to the old one.

https://user-images.githubusercontent.com/9304740/132602818-e8bdb845-5310-4ebf-b880-1a2b463c49cd.png

<img src="https://user-images.githubusercontent.com/9304740/132602818-e8bdb845-5310-4ebf-b880-1a2b463c49cd.png" height="300">

**Comment by Saransh-cpp** [comment]
Hi @guyluz11, can I take this up under hacktoberfest?

**Comment by guyluz11** [comment]
Sure @Saransh-cpp 
Will put this one on you.

**Comment by Saransh-cpp** [comment]
Hi @guyluz11, does this look good?

[<div align="center"><img alt="CyBear Jinni image" height="400" src="https://user-images.githubusercontent.com/74055102/135392416-b055135a-2b24-4076-93f4-c54d1f817912.png">](https://github.com/CyBear-Jinni/CBJ_Smart-Home)
</div>

**Comment by guyluz11** [comment]
@Saransh-cpp does the area around the phone transparent?.
If so then this is great.

**Comment by guyluz11** [comment]
Thanks @Saransh-cpp for completing the issue.

You are welcome to star the repo to show your support in our goal to make the world a better place 🌏.

**Comment by Saransh-cpp** [comment]
Sure! My pleasure!
