### ISSUE TITLE
Add play store badges to the readme

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#279]
Left to the snap badge we need to add play store badge that will take the user to the [CyBear Jinni play store page](https://play.google.com/store/apps/details?id=com.cybear_jinni.smart_home).

![image](https://user-images.githubusercontent.com/9304740/132603205-c36d82e5-e6c3-4790-a874-786ee48f9c54.png)

**Comment by Pranjalmishra30** [comment]
Hey, i can do this. Could you assign this to me.
Also is there color scheme/preference that you are following ? 
Thanks  :)

**Comment by guyluz11** [comment]
Sure @Pranjalmishra30 
There is no color scheme.

**Comment by guyluz11** [comment]
Thanks @Pranjalmishra30  completing the issue, your response was very quick.

Will close now the issue.


You are welcome to star the repo to show your support in our goal to make the world a better place earth_asia.
