### ISSUE TITLE
Convert all prints to logs

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#294]
Follow up to  #292  we now need to convert all the pints in the app to use the new log system that we have added.

Just use `logger.i('Text');` instead of `print('Text');` and import the logger function from `import 'package:cybear_jinni/utils.dart';`

Here are the types of log that you can use
```
logger.v("Verbose log");

logger.d("Debug log");

logger.i("Info log");

logger.w("Warning log");

logger.e("Error log");

logger.wtf("What a terrible failure log");
```

**Comment by Kushalrock** [comment]
I can surely do that. I have good experience with dart and flutter. This can be a great issue to start with to know more about the project and to actually contribute something on the way. After knowing about the project, I can contribute to the more complicated issues too.

**Comment by guyluz11** [comment]
Sure @Kushalrock
I will assign the issue to you, pull requests are always welcome.
You can talk to me on the CyBear Jinni Discord server if you want to know more, need any help, ask questions, talk about the code, and more.


[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)

**Comment by guyluz11** [comment]
Done
