### ISSUE TITLE
Change folder structure

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#3]
Currently the app content is located inside three folders in the path 
[CBJ_App/FlutterApp/cybear_jinni_flutter/cybear_jinni_flutter](https://github.com/CyBear-Jinni/CBJ_App/tree/master/FlutterApp/cybear_jinni_flutter/cybear_jinni_flutter).

We need to move the project back in order to remove folders that contain only one folder without purpose.

The content of the folder should move into the [CBJ-App/](https://github.com/CyBear-Jinni/CBJ_App) location (Main folder of the project).

**Comment by sohan-k** [comment]
Hey @guyluz11 , I would like to do it. Please assign me and I'll leave PR in October.

**Comment by guyluz11** [comment]
Go for it

**Comment by sohan-k** [comment]
Opened at #16 @guyluz11

**Comment by sohan-k** [comment]
Opened at #23

**Comment by guyluz11** [comment]
Tested on my phone and it is working.

I fixed the Dart CI in dev

Thanks @sohan-k
