### ISSUE TITLE
Mac app icon is incorrect

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#309]
Mac app icon is incorrect, it should be CyBear jinni icon and not the flutter icon.

**Comment by ThilinaTCH** [comment]
@guyluz11 Please assign this to me

**Comment by guyluz11** [comment]
Thanks @ThilinaTCH , you got it

**Comment by guyluz11** [comment]
Thanks for compiling another issue @ThilinaTCH 

Will close the issue now.
