### ISSUE TITLE
Detect current country code automaticly for user

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#318]
On the Tuya sign page the user needs to enter his country code.
It will be nice that it will be filled automatically for the user on page load and there will be an option to change it.

<img alt="Tuya sign in page" height="400" src="https://user-images.githubusercontent.com/9304740/136705953-ab559cf5-5a15-4505-a9fe-988e6a9db2e3.png">

**Comment by Ashwith25** [comment]
Shall I work on this?

**Comment by guyluz11** [comment]
Also found these two packages that may help
[country_code_picker](https://pub.dev/packages/country_code_picker)
[country_picker](https://pub.dev/packages/country_picker)

**Comment by UtkarshDeoli** [comment]
hey may i work on this ?? and can you tell what has been done and what else is needed to be done

**Comment by guyluz11** [comment]
Sure @UtkarshDeoli it is yours.
I have taken another look at it and I think you better start from the beginning, not sure if the staff has changed since the pr and can be done in a better way.
You can draw inspiration from the pr #321 and take a look at the comments that I have left there.

If you need any help you can ping me in the discord server of cbj
[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)
For example arriving to this page in the UI of the app.

**Comment by SanjaySargam** [comment]
Can I contribute???

**Comment by UtkarshDeoli** [comment]
@guyluz11 thank you for assigning it to me

**Comment by guyluz11** [comment]
Hi @SanjaySargam someone just took this issue, sorry.

**Comment by guyluz11** [comment]
How are you @SanjaySargam and @Julienjthomas 

This issue is already got assigned to someone.
I am working on a way to use the app in demo mode which will help make contributing to most parts of the app much easier (without setting cbj Hub and having smart devices).

So that I don't forget that you are searching issue to help please comment here #444 that you would like to get notified when it is done and would like to get Flutter issue for you

**Comment by UtkarshDeoli** [comment]
Hey @guyluz11 how about this library 
[fl_country_code_picker](https://pub.dev/packages/fl_country_code_picker)
Insted of country_picker.

And should location be used to detect the Country of a user and then assign a country code to them or should there be a default country code and the user can select their code form a dropdown if it's not the default one.

**Comment by guyluz11** [comment]
> Hey @guyluz11 how about this library [fl_country_code_picker](https://pub.dev/packages/fl_country_code_picker) Insted of country_picker.
> 
> And should location be used to detect the Country of a user and then assign a country code to them or should there be a default country code and the user can select their code form a dropdown if it's not the default one.

What are the benefits of using fl_country_cose[fl_country_code_picker](https://pub.dev/packages/fl_country_code_picker)  agins [country_picker](https://pub.dev/packages/country_picker)?

As far as I can see country_picker have much more upvotes in pub.dev.

We want to help the user so both selecting automatically for the user and let him change it using dropped down are good options that will be accepted.

In the end we prefer bouth to work together.

**Comment by guyluz11** [comment]
Hi @UtkarshDeoli  I am removing you from Assignees but your pr will still be merged if it will be accepted

Thanks

**Comment by Aaliya-Ali** [comment]
@guyluz11 
Do you want the autofilled country code to be fetched based on the user's location or a default country (say the US) or a country where majority of your users reside would work too?

**Comment by guyluz11** [comment]
@Aaliya-Ali 

I would like one of 2 things or both.

1. Field will include drop down of country with country code.
2. Field data get filled automatically based on user location

**Comment by guyluz11** [comment]
We have removed Tuya from supported devices since they have changed the API.
This feature probably will be required for other vendors in the future so when it is needed I will open a new one.

Thanks everyone.
