### ISSUE TITLE
Readme file small fixes

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#33]
Please add `alt="CyBear Jinni image"` to the CyBear Jinni image in the readme  

Like this   

[<div align="center"><img alt="CyBear Jinni image" height="300" src="https://user-images.githubusercontent.com/9304740/94843279-24a49900-0425-11eb-83f3-87e8ba40b1dc.png">](https://github.com/CyBear-Jinni/CBJ_Smart-Home)
</div>

```html
[<div align="center"><img alt="CyBear Jinni image" height="300" src="https://user-images.githubusercontent.com/9304740/94843279-24a49900-0425-11eb-83f3-87e8ba40b1dc.png">](https://github.com/CyBear-Jinni/CBJ_Smart-Home)
</div>
```

And move the badges to be above it.

**Comment by varadkulk** [comment]
I can do it

**Comment by guyluz11** [comment]
@varadkulk I will assigne it to you.

**Comment by guyluz11** [comment]
#35 

@varadkulk Thanks
