### ISSUE TITLE
Devices Scroll location changing when list size changes

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#379]
Whenever we turn devices on and off they are added and removed from the summary section, because of that the size of the list is changing and your current place in the list changes a little bit up or down.

We should keep the user in the same position that he scrolled even when new items are added or removed from the list. 

![20220508_144232](https://user-images.githubusercontent.com/9304740/167294578-77751ccf-4b3b-4c2e-b750-44f68d125d53.gif)

I have just added to the Wiki instructions on [how to get to the demo mode](https://github.com/CyBear-Jinni/cbj_app/wiki/How-to-open-app-in-demo-mode) so use it to test that.

If you need any help with that you can ask in the cbj discord server 

[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)

**Comment by Summiedev** [comment]
Please assign me this

**Comment by guyluz11** [comment]
Yours @Summiedev

**Comment by guyluz11** [comment]
Hi @Summiedev  I am removing you from Assignees but your pr will still be merged if it will be accepted

Thanks

**Comment by SankethBK** [comment]
@guyluz11  Hi, want to contribute to this. But demo mode appears to be empty

**Comment by guyluz11** [comment]
Does "Devices" tab have content?, Your screenshot is from the "Automations" tab.

If you are talking specifically about this issue than Automations tab is not essential.

If devices tab is empty than please forked dev branch.

Incase you want to have automations in the demo mode you can solve this issue and in the same place insert automations #458

**Comment by SankethBK** [comment]
@guyluz11  Devices page is also empty. I am using the latest dev branch with commit id `a9b8620fad1312d9306b6cb14e61cba00d36ecaa`
![Screenshot_1666012793](https://user-images.githubusercontent.com/51091231/196187774-788d6a83-2a52-45f0-9758-0925b198dd2e.png)

**Comment by SankethBK** [comment]
@guyluz11 facing some issues in running the app.
On Android, when i click on "off" in devices a snackbar shows up but the list item isn't getting removed from the list. I had this error on terminal `Permission to use location is denied` on both Android emulator and real device. I double checked that i have granted all location permissions. 
On iOS i was facing lot of dependency issues, so i deleted the ios folder, cleared cache and re-created it. But now the app crashes immediately after it is built with "Runner crashed unexpectedly" error message on iOS emulator. Can you please help in resolving these issues?

**Comment by guyluz11** [comment]
Of course, join the discord server and ping me.
We will work on it together

<a href="https://discord.gg/mUXfwUY">
<img align="left" alt="Discord" width="45px" src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" /></a>

**Comment by SankethBK** [comment]
Hi, i want to contribute for this issue also. Currently the changes are abrupt, after adding a little animation, this is the result, what's your opinion on this?
![cbj_gif](https://user-images.githubusercontent.com/51091231/197223871-df0d33fc-6b7d-4bf5-b11d-9150027af552.gif)

**Comment by guyluz11** [comment]
This looks interesting, can you add another gif of it happening where the summary page is not visible? (scroll up then turn on/off a device).

I think in general it is better

**Comment by SankethBK** [comment]
@guyluz11 summary page would be empty as before if no devices are on. 

<img src="https://user-images.githubusercontent.com/51091231/197268958-c2229a43-8b58-4c90-b85b-b5a2f36d79a1.gif" width="300" />

**Comment by guyluz11** [comment]
I meant something else.
Would you be free tomorrow to show me it with a shared screen in discord?

**Comment by SankethBK** [comment]
Let me know at what time you would be available

**Comment by guyluz11** [comment]
@SankethBK your scroll animation in the pr looks good and addresses the problem in another way that improves the experience for the user.

Thanks for the pr, will close this issue now.
