### ISSUE TITLE
Move parts in readme

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#38]
In the project readme.md file please move the `disclaimers` part below `Social Media Links` part.

https://github.com/CyBear-Jinni/CBJ_App#disclaimers

**Comment by GuillaumeFalourd** [comment]
Hi @guyluz11 , can assigned this issue to me please ?

**Comment by guyluz11** [comment]
Sure

**Comment by guyluz11** [comment]
Thanks for the pull request @GuillaumeFalourd 

Will now close this issue.
