### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#398]
Please update all project dependencies to the last version.

As you probably know the project dependency versions exist in the [pubspec.yaml](https://github.com/CyBear-Jinni/cbj_app/blob/master/pubspec.yaml) file

**Comment by FireNdIce3** [comment]
Can I work on this issue?

**Comment by guyluz11** [comment]
> Can I work on this issue?

Sure

**Comment by superiorsd10** [comment]
@guyluz11 Hey! Can I work on this issue?

**Comment by guyluz11** [comment]
> @guyluz11 Hey! Can I work on this issue?

Someone else is already assigned to this issue but I have a similar issue for you in another repo.
Comment here https://github.com/CyBear-Jinni/cbj_hub/issues/175 that you would like to take the issue.

**Comment by FireNdIce3** [comment]
@guyluz11 Hii. I have opened a PR and updated the dependencies. Can you please look into it?

**Comment by guyluz11** [comment]
@FireNdIce3 thanks for pr.
It got merged so I am closing the issue now.

Happy Hacktoberfest :)
