### ISSUE TITLE
Fix Flutter action in the project

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#4]
Currently the [Flutter action](https://github.com/marketplace/actions/flutter-action) is not working.

[This is the file](https://github.com/CyBear-Jinni/CBJ_App/blob/master/.github/workflows/dart.yml) of the implementation of it in the project.

Line on crash:

```
 tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/usr/bin/tar: Child returned status 2
/usr/bin/tar: Error is not recoverable: exiting now
Error: The process '/usr/bin/tar' failed with exit code 2
```

As this is my first time working with GitHub Flutter Action I may have basic thing that I missing in the process.

**Comment by duythien0912** [comment]
Can I take it too, will create as soon as Hacktoberfest starts 😆

**Comment by guyluz11** [comment]
Assigneeing it to you @duythien0912  
Thanks

**Comment by guyluz11** [comment]
Thanks @duythien0912 

The tests are now passing.

[<img src="https://user-images.githubusercontent.com/9304740/94795124-98bf4c80-03e5-11eb-9f3e-082e3c233a1a.png" height="300">](https://discord.gg/mUXfwUY)
