### ISSUE TITLE
Differences between Supported vendor's logo

### ISSUE THREAD

**Issue by harshit-maheshwari** [CyBear-Jinni/cbj_app#412]
![image](https://user-images.githubusercontent.com/55666814/193453753-554eb332-b79c-4110-8830-498b6f024366.png)
While checking the website I found out that the Supported vendor's logo present in the website have this uneven organization of border radius, which is reducing the appeal of the website as well as this disorganized border radius will impact the end-user negatively.  
 
This issue can be resolved using a small change in the CSS of the file or we can also add few more styling to the logos to make it more appealing and easy for the eyes of the end-user.

**Comment by harshit-maheshwari** [comment]
I am able to work on this, Please assign this issue to me!

**Comment by guyluz11** [comment]
I believe this can help the site look better.

We can make all the borders radius the same as the red one (Yeelight) and that will make it look better.

@harshit-maheshwari  you have mentioned CSS but this repo uses an entirely different technology named Flutter.
If that is still something that you can handle I will gladly assign the issue to you.

**Comment by harshit-maheshwari** [comment]
Yes! I am able to do this task in flutter too, it requires basic knowledge of dart and I am able to correct this issue.

**Comment by guyluz11** [comment]
It is yours

**Comment by guyluz11** [comment]
@harshit-maheshwari the repo of the site exists here
https://github.com/CyBear-Jinni/CBJ_Site

Can you open the same issue there?, this repo is about the app and it will be wrong to keep the conversation here.

Thanks
