### ISSUE TITLE
Adding Firebase support for IOS (Xcode is needed)

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#42]
We are going to start supporting IOS for our Flutter app 🥳.

I never ran the app on IOS so I would love to see screenshots how does it look.

You will need to use Xcode in order to import the [GoogleService-Info.plist](https://github.com/CyBear-Jinni/CBJ_App/files/5321422/GoogleService-Info.plist.zip) file for Firebase configuration.

Please add Firebase support for IOS and make sure that it is working.

**Comment by WaAlvis** [comment]
Hello, I would like to work on the task, you assign it to me

**Comment by guyluz11** [comment]
You got it @WaAlvis 

If you need help you can join the Discord server I am there

[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)

**Comment by guyluz11** [comment]
Can you show me the "problems" maybe I can help. 
I am in the discord now.

**Comment by guyluz11** [comment]
Uploading the error
![error](https://user-images.githubusercontent.com/9304740/95637232-e6008580-0a99-11eb-80a9-cb93e1a8c08c.png)

**Comment by guyluz11** [comment]
We are now supporting iOS on dev
![signal-2021-01-31-200153](https://user-images.githubusercontent.com/9304740/106396401-5ac44a80-6410-11eb-837d-8b6c37a497f1.jpg)
![signal-2021-01-31-200211](https://user-images.githubusercontent.com/9304740/106396403-5bf57780-6410-11eb-9862-f19c8cd913fc.jpg)
