### ISSUE TITLE
Readme file missing most of the Social Media Links

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#429]
Readme file missing most of the Social Media Links

![image](https://user-images.githubusercontent.com/9304740/193541356-2f798a89-962c-4322-aea9-7890a7c25d37.png)

As you can see at the bottom of our site we have accounts on many more social media platforms.

https://cybearjinni.com/#/

![image](https://user-images.githubusercontent.com/9304740/193541720-c348c41c-f738-448e-9ab1-3404830b7715.png)

Please add links and icons with all the platforms to the readme file.

**Comment by guyluz11** [comment]
It is yours @Mahich123

**Comment by Mahich123** [comment]
Great !! Keeping the social media icons in this order as you shown at the image . And can you share the links ?

**Comment by adityar224** [comment]
Hey I Didn't see this and have already raised a pull request 😢

**Comment by Mahich123** [comment]
> Hey I Didn't see this and have already raised a pull request 😢

Ohh ! I also did showing merge blocked 
@guyluz11  can you check it please .

**Comment by guyluz11** [comment]
Thanks
