### ISSUE TITLE
Make demo mode load the app with devices

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#444]
Currently we have a demo mod button in the app.

It bypasses finding the Hub screen but does not show any devices.

Loading the app in demo mode with devices can help new users get an impression of the app without setting the Hub up (or without having smart devices), it will also help developers work on the app without the hassle to set up a cbj Hub just for contributing. 

It will open much more options and easy app readings and improved UI.

** Everyone that would love to get a Flutter issue in this repo can comment here and when this issue is done I will have much more issues to share with you. **

**Comment by guyluz11** [comment]
Done thanks

**Comment by UtkarshDeoli** [comment]
Hey if there are more issues under hacktober that are good for biggners please inform me when u open the issue.
