### ISSUE TITLE
Demo mode devices are hard coded

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#458]
I have just pushed the demo mode of the app and I used hard-coded values for the devices.

This is bad practice as we all know XD.

Please change the hard coded devices string that comes from the Hub (in demo mode).

You should create an object of that device with all the corresponding values, then use `.toDts` on it and then use `.toJsonString`.

https://github.com/CyBear-Jinni/cbj_app/blob/0cbb6be1ea3606829746d788961bf7f48ac400d2/lib/infrastructure/hub_client/hub_client_demo.dart#L85

Should look like this 

```dart
GenericBlindsDE guyBlinds = GenericBlindsDE(...);
DeviceHelper.convertDomainToJsonString(guyBlinds);

 String allRemoteCommandsBlinds = DeviceHelper.convertDomainToJsonString(guyBlinds);
```

I have just added to the Wiki instructions on [how to get to the demo mode](https://github.com/CyBear-Jinni/cbj_app/wiki/How-to-open-app-in-demo-mode) so use it to test that the app behaves the same

If you need any help with that you can ask in the cbj discord server 

[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)

**Comment by Simran1604** [comment]
Hey! I'd like to take this up

**Comment by guyluz11** [comment]
Yours @Simran1604

**Comment by guyluz11** [comment]
Hi @Simran1604  I am removing you from Assignees but your pr will still be merged if it will be accepted

Thanks

**Comment by mufida1018** [comment]
I would like to contribute

**Comment by guyluz11** [comment]
@mufida1018 feal free to open pr for that, for any help I am in the discord server of CyBear Jinni

**Comment by SankethBK** [comment]
#554

**Comment by guyluz11** [comment]
Done thanks
