### ISSUE TITLE
Login with remote pipes

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#461]
Currently you can log into the app in two ways

By setting a CBJ hub the app detected it in the local network and connect to it.

By opening demo mode of the app with mock devices.

Cbj remote pipes lets you connect to a hub through a domain.
Currently the app already support connecting through CBJ remote pipes but only after login to a hub in the local network.

The screen to login to the remote pipe already exist
So only the form for remote pipe url and small logic change are needed

**Comment by rktejesh** [comment]
Hi @guyluz11 
Can I work on this issue?

**Comment by guyluz11** [comment]
Will be added in the future, for you can add remote pipes only after the phone finds devices in the local network
