### ISSUE TITLE
Readme cbj hub link is incorrect

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#473]
I have found out that the link to CBJ hub repo in the readme file is incorrect.

Currently getting to cbj smart device which is wrong.

The linked should change to this 

https://github.com/CyBear-Jinni/cbj_hub

Take it only if you're ready to complete it in the next few hours as this is important.

**Comment by guyluz11** [comment]
@techsnap sure
Please complete it asp as this is important to fix

**Comment by techsnap** [comment]
Sure!

**Comment by techsnap** [comment]
Hey, project's contributing.md file says to open pull request to dev branch instead of master. Should I also fork dev branch and make a new branch for myself from dev instead of master?

**Comment by guyluz11** [comment]
PR got merged.

Will close the issue now
