### ISSUE TITLE
Page:(Connect to Hub) Issue:(pixel over flow when keybord is opened)

### ISSUE THREAD

**Issue by UtkarshDeoli** [CyBear-Jinni/cbj_app#483]
![photo_2022-10-04_22-18-55](https://user-images.githubusercontent.com/89682101/193879360-7545cca9-3b03-4f25-af42-f20c573b182c.jpg)

There is a overflow of 180 pixels at the bottom when keybird is opened

**Comment by UtkarshDeoli** [comment]
hey can u assign this to me under Hacktober ?

**Comment by guyluz11** [comment]
Sure @UtkarshDeoli and nice keyboard 😉

**Comment by UtkarshDeoli** [comment]
Thank You 😊😁

**Comment by ashishmohapatra240** [comment]
Hey, I would like to work on this!

**Comment by guyluz11** [comment]
> Hey, I would like to work on this!

Sorry @UtkarshDeoli but this issue got already assigned.to someone else.

**Comment by guyluz11** [comment]
@UtkarshDeoli My bad 😅

@ashishmohapatra240  sorry but this issue got already assigned to someone else.

**Comment by ashishmohapatra240** [comment]
Oh Yeah! 😅

I understand

**Comment by guyluz11** [comment]
Pr got merged, will close this issue now thanks
