### ISSUE TITLE
Software Info text is out of bound

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#487]
The text in the Software Info screen is out of bounds 

To arrive at the screen

1. Open the app in [demo mode](https://github.com/CyBear-Jinni/cbj_app/wiki/How-to-open-app-in-demo-mode).
2. Click the + button at the bottom of the screen
3. Click on `Software Info` orange button

<img alt="CyBear Jinni image" height="400" src="https://user-images.githubusercontent.com/9304740/193900181-60f339d6-4ca8-4e9d-a271-101fbdec9d05.jpg">

<img alt="CyBear Jinni image" height="400" src="https://user-images.githubusercontent.com/9304740/193900176-e5b174b4-ea8b-4785-ae0b-92c2f201d5c9.jpg">

**Comment by AdityaKeshan** [comment]
please assign

**Comment by guyluz11** [comment]
@AdityaKeshan yours

**Comment by AdityaKeshan** [comment]
Thanks

**Comment by ashishmohapatra240** [comment]
Hey, I would like to work on this!

**Comment by AdityaKeshan** [comment]
<img src="https://user-images.githubusercontent.com/60391695/194048991-edcc008d-e36c-41a0-afb9-cb433e203650.png" width="300" height="600">
Does this look good?

**Comment by AdityaKeshan** [comment]
okay working on it. Anything else?

**Comment by AdityaKeshan** [comment]
<img src="https://user-images.githubusercontent.com/60391695/194109057-0f4764d9-7e34-4198-bec5-7725c8b0280e.png" width="300" height="600">
If its okay i will put a PR

**Comment by guyluz11** [comment]
Yep thats good

**Comment by guyluz11** [comment]
Pr got merged.

Will close this issue now 

Thanks

**Comment by guyluz11** [comment]
Hi @ashishmohapatra240 this feature got already assigned to someone else.

You are more than welcome to test and work on the Hub.

The app connects to the Smart Hub, and currently requires much more attention than it gets.
https://github.com/CyBear-Jinni/cbj_hub

You can test it and find issues, add support for new integration with smart devices, or improve an existing one.

Now that I think about it maybe we should add in the app a way to add a fake device so that testers without smart device in their home can test the Hub.

Feel free to discuss this with me about it on the discord server of cbj 
<a href="https://discord.gg/mUXfwUY">
<img align="left" alt="Discord" width="45px" src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" /></a>
