### ISSUE TITLE
Change readme logo url

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#49]
Current logo in readme have space in the top of the image.

I have created new one without that, pleas update the readme to the new one and update the height to 400

[<div align="center">
<img alt="CyBear Jinni image" height="400" src="https://user-images.githubusercontent.com/9304740/95004821-f8417600-05f8-11eb-95bb-60a7863364e0.png">](https://github.com/CyBear-Jinni/CBJ_Smart-Home)
</div>

```
[<div align="center">
<img alt="CyBear Jinni image" height="400" src="https://user-images.githubusercontent.com/9304740/95004821-f8417600-05f8-11eb-95bb-60a7863364e0.png">](https://github.com/CyBear-Jinni/CBJ_Smart-Home)
</div>
```

**Comment by bansodeashish24** [comment]
I would like to take this up.

**Comment by guyluz11** [comment]
@bansodeashish24 
Thanks 
Will now close the issue
