### ISSUE TITLE
Add login with Firebase to the flutter app

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#5]
We are currently have a non working login page located [here](https://github.com/CyBear-Jinni/CBJ_App/blob/master/FlutterApp/cybear_jinni_flutter/cybear_jinni_flutter/lib/features/login_page/login_page.dart).

Pressing the "Log In" button just passing the user to the next page without any validation that the credentials exist in the Firebase users database.

We need to
- [x] Add request to Firebase to check if user exist.
- [x] Login automatically if the user have logged in before.

**Comment by sagarchoudhary96** [comment]
@guyluz11 i would like to work on this issue. can you assign it to me.

**Comment by guyluz11** [comment]
@sagarchoudhary96 Sounds good.
 
For developing the Firebase you do need to go over the instructions (although written differently) because the app already have small Firebase parts.

Just complete the [instructions-for-developers](https://github.com/CyBear-Jinni/CBJ_App/tree/master#instructions-for-developers) in the readme, that should be enough.

**Comment by guyluz11** [comment]
@sagarchoudhary96 If you have any questions you can reach me in the [CyBear Jinni Discord channel](https://discord.gg/RwsB7K).

**Comment by sagarchoudhary96** [comment]
sure will do👍

**Comment by elaishane** [comment]
I would also like to work on this issue. Could I join too?

**Comment by guyluz11** [comment]
Hy @elaishane currently @sagarchoudhary96 is assigned to this task so he will update you here in case he need help with that.

I would like your help review his pull request if you can.

I am creating new issue to create the the "Forgot password?" page, do you want me to assign it to you?.

<img src="https://user-images.githubusercontent.com/9304740/94589741-56372c00-028e-11eb-9193-351321dd73b4.jpeg" height="300">

**Comment by elaishane** [comment]
Yes please assign me on forgot password

**Comment by guyluz11** [comment]
@elaishane  please leave a comment [on the ticket](https://github.com/CyBear-Jinni/CBJ_App/issues/13) as github don't let assign you without that.

**Comment by guyluz11** [comment]
@sagarchoudhary96  @elaishane 

As I want to have the easiest way for peoples to make their smart home I have two questions about Firebase, please let me now if you think this is possible.

1. Currently we have the file [constant_credentials.dart](https://github.com/CyBear-Jinni/CBJ_App/blob/master/FlutterApp/cybear_jinni_flutter/cybear_jinni_flutter/lib/core/constant_credentials.dart) and the developer need to insert the details there manually from the `google-services.json` file.
We need this in order to set the Smart Devices when connecting to them for the first time. 

Do you think that we can extract the "project_id" and "api_key" fields from `google-services.json` programmatically in runtime?.

2. I want my app to be in the store but to have the same app the option to use other peoples Firebase.
I am imagining easy interface that have button to upload their `google-services.json` from the phone.

Do you think that we can upload a `google-services.json` and use it to connect to Firebase with it after the program was already compiled to apk?.

If we solve both of them the readme instructions will be very short and easy for new users and developers.

**Comment by sagarchoudhary96** [comment]
@guyluz11 
1. I think it should be easily possible to read values from `google-services.json` file and make you of it directly instead of storing them in the `constant_credentials.dart` file .

2. i don't think it would be possible, also if you are publishing the app then as a developer it should make use of your firebase DB rather then each user creating their own firebase accounts.

**Comment by guyluz11** [comment]
@sagarchoudhary96  

For the first one I created an issue as I thought that it is possible.

For the second one this is a bummer.
I wanted that by default the user will use my Firebase in the app but will have the possibility to change it. 

Thanks for the second opinion.

**Comment by guyluz11** [comment]
Update!

A default test `google cloud Firebase` configuration was add to the app so for developers you only need to run the app on the phone and it should work.

Thanks

**Comment by guyluz11** [comment]
#59 is part of it

**Comment by guyluz11** [comment]
This is big step forward for the app, thanks @sagarchoudhary96 for all the work.
 
Will now close this commit
