### ISSUE TITLE
Deprecated methods

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#535]
Both 

`getLocationServiceAuthorization`
and
`requestLocationServiceAuthorization`

Are deprecate.

https://github.com/CyBear-Jinni/cbj_app/blob/426d29b431ea514c70506a15f8d5e02cfebc9d30/lib/infrastructure/core/shared_methods.dart#L17

Please fix deprecated methods

**Comment by AlgyJr** [comment]
Hi @guyluz11 I'd like to resolve this issue, can you assign it to me?

**Comment by guyluz11** [comment]
> Hi @guyluz11 I'd like to resolve this issue, can you assign it to me?

Just open pr to dev for that and I will accept it when it is ready :)

**Comment by guyluz11** [comment]
Pr got merged.

Thanks
