### ISSUE TITLE
Create 'Create new account' page 

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#6]
Currently the [login page](https://github.com/CyBear-Jinni/CBJ_App/blob/master/FlutterApp/cybear_jinni_flutter/cybear_jinni_flutter/lib/features/login_page/login_page.dart) is missing a way to create new account.

Please add new text button "Create new account" above the 'Forgot password?'  button.

The new text should send you to new page that will show the user registration screen.

In the registration screen the following fields are required: Email, Password. 

For now the actual registration logic **is not required to be created**.

**Comment by duythien0912** [comment]
can I take this issue as soon as Hacktoberfest starts?

**Comment by guyluz11** [comment]
Sure :)

**Comment by guyluz11** [comment]
#15 
Done Thanks
