### ISSUE TITLE
ADD button is out of screen in "Add New Area" page

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#616]
Same as  #614 but on the "Add new Area" screen.

The "ADD" button is getting out of the screen when there are a lot of tags

Ok

<div align="center"><img alt="App photo" height="400" src="https://user-images.githubusercontent.com/9304740/200169834-d70d5300-e05e-4a38-aa3c-f2a3a5d79d95.png">
</div>

Is out of the screen

<div align="center"><img alt="App photo" height="400" src="https://user-images.githubusercontent.com/9304740/200169797-174cf6b4-2188-4852-8f0e-01d79331d564.png">
</div>

**Comment by SankethBK** [comment]
Sure, i will take this up

**Comment by SankethBK** [comment]
@guyluz11 how to reach this screen?

**Comment by guyluz11** [comment]
![Screenshot_20221108-113843](https://user-images.githubusercontent.com/9304740/200529915-6b037bbd-9aff-417f-90c4-e20e9b4ca04f.jpg)
![Screenshot_20221108-113848](https://user-images.githubusercontent.com/9304740/200529928-d86f64c6-7473-4246-a567-cbc3361f94bb.jpg)

**Comment by SankethBK** [comment]
Thank you

**Comment by guyluz11** [comment]
Thanks pr got merged, closing issue
