### ISSUE TITLE
Area automation background

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#617]
Currently, our automation scenes tab looks like this

<div align="center"><img alt="App photo" height="400" src="https://user-images.githubusercontent.com/9304740/200172481-d516491d-e0fd-4ab8-9eea-ad583e464e2d.png">

And whenever we open one of the scenes it looks like this

<div align="center"><img alt="App photo" height="400" src="https://user-images.githubusercontent.com/9304740/200172501-b0dfc324-b449-46fc-9e51-3b0a3ea7d666.png">

We can improve the look of this by making the area image a background like this

<div align="center"><img alt="App photo" height="400" src="https://user-images.githubusercontent.com/9304740/200172617-1ad58188-822d-4921-9ea8-d4dbfe282f55.png">

**Comment by Manty-K** [comment]
Please assign me this issue

**Comment by Priyanshu-Maikhuri** [comment]
Hi @guyluz11,  Do you mean to add an image in the top empty position of the first two screens above? Please explain the issue more as I'm interested in resolving this issur.

**Comment by guyluz11** [comment]
Sorry but this issue has already got solved, thanks
