### ISSUE TITLE
rgbW light text out of bounds

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#619]
Whenever a rgbW light have long text it is getting out of bound

![Screenshot_20221109-125742](https://user-images.githubusercontent.com/9304740/200817647-14359e4f-da16-4623-b2e0-beadf75d69f7.jpg)

**Comment by chandansgowda** [comment]
Hey @guyluz11 
Shall I take this up?

**Comment by guyluz11** [comment]
Sure, if you need any help l am at the discord server

https://discord.gg/mUXfwUY

**Comment by chandansgowda** [comment]
Hey @guyluz11 
Please review my PR - #623 
Thanks

**Comment by guyluz11** [comment]
I see that the fix pr got marged and I forgot to close this issue.

I'll go ahead and close this issue now.

Thanks :)
