### ISSUE TITLE
Logo in readme need some editing

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#62]
We have logo of CyBear Jinni in the readme.
CyBear Jinni have the following repository's `Smart Device`, `App`, `Smart Home` so we need some change to the logo to distinguish between them. 

For the `App` I suggest to put the logo inside a phone

<img src="https://user-images.githubusercontent.com/9304740/95074711-afccaa00-0717-11eb-993d-c08ee587b9f4.jpeg" height="400">

This is a mock that I created, you can use it or be creative and do better one and take it to whole new place.

**Comment by 3t8** [comment]
I wanted to put the logo on a darker background but there's some white around the edges, the selection is a little fuzzy. Do you have the original logo file in a better quality so I can redo the selection?

**Comment by guyluz11** [comment]
Hi @3t8 
[This is](https://github.com/CyBear-Jinni/CBJ_Site/blob/master/fan_art/CyBear_Jinni_art_3.jpeg) the original.

I will assign the issue to you.

**Comment by 3t8** [comment]
If you want, I can also help with the logos for smart home and smart device.
Can I upload an upscaled and a better png crop of the logo in the fan_art folder?

**Comment by guyluz11** [comment]
> If you want, I can also help with the logos for smart home and smart device.

Sure, this is the links to the issues [`Smart Home`](https://github.com/CyBear-Jinni/CBJ_Smart-Home/issues/104), [`Smart Device`](https://github.com/CyBear-Jinni/CBJ_Smart-Device/issues/62).




> Can I upload an upscaled and a better png crop of the logo in the fan_art folder?

Yes, please create new folder inside the [`fan_art`](https://github.com/CyBear-Jinni/CBJ_Site/tree/master/fan_art) and call it `after_editing` and save it there.

**Comment by guyluz11** [comment]
Hi @3t8 
I merged your pull request and will close this issue now.
If you decided to take the `Smart Home` and `Smart Device` as well please comment on the issues so that I will be able to assign it to you.

Thank you.
