### ISSUE TITLE
Change welcome screen according to the new moc

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#624]
Our welcome screen will get some changes to be more appealing.

Let's change it to look like the new moc, and use the current CyBear Jinni logo.

Our current welcome screen 

![Screenshot_20221115-154637](https://user-images.githubusercontent.com/9304740/201935661-87f094c5-4021-467d-953b-8ac854a4023a.jpg)

Our new moc

![image](https://user-images.githubusercontent.com/9304740/201934306-c66f4957-d8ce-4133-be49-c9ff9b263806.png)

Instead of the text at the bottom keep the current changing text animation that we have

**Comment by gantanikhilraj** [comment]
If it is not finished, you can assign it to me.

**Comment by guyluz11** [comment]
Cool, go for it

When it is ready open PR to dev please

**Comment by guyluz11** [comment]
Done
