### ISSUE TITLE
New moc for connected to Hub page

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#625]
We got a new moc for Connect to Hub page.
Let's change the current one to look like this

Current screen

![Screenshot_20221115-154703](https://user-images.githubusercontent.com/9304740/201935497-0fac6555-a970-4c83-8ef9-45446bebd262.jpg)

Our new moc 

![image](https://user-images.githubusercontent.com/9304740/201934815-e8dd49c3-dcd8-4aa5-bc0b-8e1ff48f854b.png)

**Comment by Manty-K** [comment]
Please assign me
