### ISSUE TITLE
Upgrading to flutter 3.7.0

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#632]
A [new release of flutter](https://medium.com/flutter/whats-new-in-flutter-3-7-38cbea71133c)  just got out 🎉.

Let's update to this version and fix the deprecated parts.

Also let's add support for material design 3 by adding 
```dart
     useMaterial3: true,
```
To `ThemeData`

**Comment by parjanya-rajput** [comment]
Is this issue still open? Can I work on it

**Comment by guyluz11** [comment]
Yes it is, feel free

This will change some of it the default themeing,  it's okay to change them as long as they're looking good

**Comment by guyluz11** [comment]
> Is this issue still open? Can I work on it

.

**Comment by parjanya-rajput** [comment]
I think I have solved the issue, can you assign me then I will do the PR

**Comment by parjanya-rajput** [comment]
Also can you mark this issue as Hacktoberfest-accpted it will be a great help :)

**Comment by guyluz11** [comment]
> Also can you mark this issue as Hacktoberfest-accpted it will be a great help :)

Where is the pr?

**Comment by parjanya-rajput** [comment]
I thought once I get assigned with this issue then I will raise PR, nvm I have raised it now. Sorry for inconvenience

**Comment by guyluz11** [comment]
Thanks

**Comment by guyluz11** [comment]
Thanks
