### ISSUE TITLE
Comment from the docs 

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/cbj_app#653]
Inside `main.dart`  file we have this comment (line 93): 

![image](https://github.com/CyBear-Jinni/cbj_app/assets/34707669/3cee4b19-da41-4644-9888-b9ebfa1e609d)

Do we need it? this is the comment from the documentation of [easy_localization](https://pub.dev/packages/easy_localization)

**Comment by guyluz11** [comment]
Nope we can remove it

**Comment by guyluz11** [comment]
Pr for Hacktoberfest?

**Comment by TMuthu** [comment]
Can i work on this?

**Comment by guyluz11** [comment]
> Can i work on this?

Sure
