### ISSUE TITLE
Add issue and pull request template 

### ISSUE THREAD

**Issue by andoriyaprashant** [CyBear-Jinni/cbj_app#659]
## Description 

**Issue Template:** It helps users report issues and request features more effectively by guiding them to provide essential information. This improves issue quality and community standards on GitHub.

**Pull Request Template:** This structured format streamlines the contribution process. Contributors can provide necessary details about their changes, related issues, and completed tasks. It promotes organized and well-documented pull requests, enhancing collaboration and GitHub standards.

## Screen Shots -

![image](https://github.com/CyBear-Jinni/cbj_app/assets/121665385/a9e0a4e6-1b26-488d-bb08-431e13ec7d78)

**Comment by guyluz11** [comment]
Why not, let's do this.
Do you want to make PR for that?

**Comment by andoriyaprashant** [comment]
Yes @guyluz11 sir, please assign this issue to me. I will create a pull request for it as soon as possible

**Comment by guyluz11** [comment]
We have shifted to just opening PR without assigning :)

**Comment by guyluz11** [comment]
Thanks 👍
