### ISSUE TITLE
Add Dependabot for Flutter Dependency Updates

### ISSUE THREAD

**Issue by andoriyaprashant** [CyBear-Jinni/cbj_app#661]
## Description

I propose integrating Dependabot into our Flutter project to automate dependency updates. Dependabot will regularly check for updates, ensuring we stay current with the latest features and security patches. This will save time, enhance security, and maintain consistency in our development process.

**Comment by guyluz11** [comment]
Sounds great

**Comment by guyluz11** [comment]
Thanks for the pr :D
