### ISSUE TITLE
Upgrade all pacakges to last version

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_app#665]
Please upgrade all packages to the last version and make sure the app runs without errors

**Comment by radar101** [comment]
I would like to work on this issue under hacktoberfest.

**Comment by guyluz11** [comment]
> I would like to work on this issue under hacktoberfest.

Sounds great, waiting for PR 😁

**Comment by Niranjan-Dorage** [comment]
Is there any issue to work on ?

**Comment by radar101** [comment]
@guyluz11 Should I create PR for the same?

**Comment by guyluz11** [comment]
Done, thanks everyone
