### ISSUE TITLE
Update contribution.md File

### ISSUE THREAD

**Issue by andoriyaprashant** [CyBear-Jinni/cbj_app#674]
## Description

The current contribution guidelines in the contribution.md file need to be updated to better reflect our project's development process and standards. This will ensure that contributors have clear and up-to-date information on how to participate in our project effectively.

**Comment by andoriyaprashant** [comment]
Hey @guyluz11 Please review my pull request #678 thank you

**Comment by guyluz11** [comment]
Thank you, pr gor merged
