### ISSUE TITLE
Add Code of Conduct File

### ISSUE THREAD

**Issue by andoriyaprashant** [CyBear-Jinni/cbj_app#680]
I would like to request the addition of a Code of Conduct file to our repository. A Code of Conduct is an essential document that outlines the expected behavior and guidelines for contributors and maintainers within our open-source community. It helps create a safe, respectful, and inclusive environment for all participants.

Having a Code of Conduct in place is not only a best practice but also demonstrates our commitment to fostering a welcoming and diverse community around our project. It sets clear expectations for interactions, promotes professionalism, and ensures that all individuals, regardless of background, feel valued and respected.

Additionally, implementing this will contribute to the improvement of our project's community standards.

![image](https://github.com/CyBear-Jinni/cbj_app/assets/121665385/bd7dba1e-3cbf-42a5-849b-c7c777352fb0)

**Comment by guyluz11** [comment]
Thanks
