### ISSUE TITLE
Add Flutter Ci 

### ISSUE THREAD

**Issue by andoriyaprashant** [CyBear-Jinni/cbj_app#681]
Proposing the inclusion of a Flutter CI workflow in our CyBear-Jinni repository. This implementation will facilitate the automatic testing and deployment of our Flutter application, enhancing the stability and reliability of our development process. This addition carries significant value, streamlining our workflow, and elevating the overall quality of our application. Kindly consider assigning this task to me for implementation if you share this perspective. Your support is greatly appreciated.

**Comment by guyluz11** [comment]
PR got merged, thanks
